#!/usr/bin/env bash

secret_cmd="secret"

keys=$($secret_cmd -l)

selected=$( printf "$keys" | rofi -dmenu -p "Secret:" )

if [[ "$selected" == "" ]]; then
    exit 1
fi

secret=$($secret_cmd $selected)

printf "$secret"

